#
# Makefile for the swift specific files
#

obj-y += board-swift.o
obj-y += board-swift-keypad.o
obj-y += board-swift-gpio-i2c.o
#obj-y += board-swift-bl-rt9393.o
obj-y += board-swift-bl-rt9393_mc.o
obj-y += board-swift-vibrator.o
obj-y += board-swift-frst_indicator.o
obj-y += board-swift-leds.o
obj-y += board-swift-msensor-bma150.o
obj-y += board-swift-ec-ak8973.o
obj-$(CONFIG_SWIFT_BATTERY_STUB) += lge_battery_stub.o
obj-$(CONFIG_FB_MSM_MDDI_SWIFT_PANEL) += board-swift-ss-driveric-panel.o
obj-$(CONFIG_FB_MSM_MDDI_SWIFT_PANEL) += mddi_ss_driveric_innotek.o
obj-y += board-swift-ers.o
obj-y += lge_errorhandler.o
obj-y += board-swift-headset.o
obj-y += board-swift-msm-touch.o 
#obj-y += board-swift-msm-ts.o
obj-y += cal_algorithm.o
obj-y += board-lge-measure-perf.o
obj-y+= board-swift-bt.o
